<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmd8VgJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmd8VgJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXmd8VgJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXmd8VgJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXmd8VgJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xmd8VgJ',
    'container.build_id' => '5f705f2b',
    'container.build_time' => 1748265800,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmd8VgJ');
