# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection: false

    csrf_protection:
        enabled: false
        stateless_token_ids:
            - submit
            - authenticate
            - logout
