security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      anonymous: true  # Autorise accès anonyme (ex: page login)
      
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: quiz_global

      logout:
        path: /logout
        target: /login

      # switch_user: true # si besoin

  access_control:
    - { path: ^/quiz, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
      app_user_provider:
        entity:
          class: App\Entity\User
          property: email

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
        lazy: true
        provider: app_user_provider

        anonymous: true

        form_login:
          login_path: app_login
          check_path: app_login
          default_target_path: quiz_global

        logout:
          path: /logout
          target: /login

    access_control:
      - { path: ^/quiz, roles: ROLE_USER }
      - { path: ^/admin, roles: ROLE_ADMIN }
