services:
  - type: web
    name: myquiz-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear --env=prod
      php bin/console assets:install --env=prod
    startCommand: |
      php bin/console doctrine:migrations:migrate --env=prod --no-interaction
      symfony server:start --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myquiz-db
          property: connectionString
      - key: MAILER_DSN
        value: null://localhost
      - key: OPENAI_API_KEY
        value: ""
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: myquiz-db
    plan: free
    databaseName: myquiz
    user: myquiz_user 